Bookstore: add reducers and actions
svitalis123/bookstore pull request #2
Opened 2022-11-07 22:10 UTC by svitalis123

# Bookstore: add reducers and actions
## I accomplished

- [ ] Created a branch
- [ ] Installed reducer using `npm i react-redux @reduxjs/toolkit`
- [ ] Add reducer using duck pattern
- [ ] Configure store
- [ ] Wrap my app with provider

2022-11-07 23:20 UTC, ShadyShawkat requested changes
## Hi @svitalis123, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 23:20 UTC, ShadyShawkat commented on src/redux/books/books.js
> +const BOOKREMOVED = 'redux/books/removeBook';
- [ ] [OPTIONAL] Kindly edit the action type to better follow the duck pattern. You can fix it by using `'bookstore/books/addBook'` instead of `'redux/books/addBook'`.

2022-11-07 23:20 UTC, ShadyShawkat commented on src/redux/books/books.js
> +};
- [ ] Kindly set the initial state in the books reducer to an empty array instead of an object, as per [this](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/add_reducers_an_actions.md#:~:text=Set%20the%20initial%20state%20to%20be%20an%20empty%20array%20of%20books.) requirement. What you've done here is not wrong. However, it can, later on, cause errors and bugs in your project so it's better to fix it beforehand.

2022-11-07 23:20 UTC, ShadyShawkat commented on src/redux/books/books.js
> +export const removebook = () => ({ type: BOOKREMOVED });
- [ ] [OPTIONAL] In order for the action creators to work properly you need to pass in the appropriate parameter to each one according to its functionality.

- [HINT] So let's say we want to fix the `addbook` action creator, it would be written as follows:
```javascript
export const addbook = (payload) => ({ type: BOOKADDED, payload });
```

- The `payload` here represents the newly added book that can be passed to the action and down to the reducer.

2022-11-07 23:20 UTC, ShadyShawkat commented on src/redux/books/books.js
> +      ];
- [ ] Please make sure that the `BOOKADDED` action adds a `book` item to the existing array of books.

- [HINT] If the new book item was passed to the reducer in a `payload` object, we can then add it to the existing array of books this way:
```javascript
case BOOKADDED:
   return [
      ...state,
      action.payload
   ];
```
This only works if the `state` is an array since we're using the spread operator here. If the state is an object that contains a books array you'll then have to use `...state.books,`.

2022-11-07 23:20 UTC, ShadyShawkat commented on src/redux/books/books.js
> +      ];
- [ ] Kindly make sure that the `BOOKREMOVED` changes the state and filters out the removed book. You can use the [`filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) array method to filter out the removed book.

2022-11-08 07:18 UTC, m05e5 requested changes
Hi @svitalis123 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)

## Highlights
✔️ your linters are all ok
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 07:18 UTC, m05e5 approved these changes

2022-11-08 07:20 UTC, merged

2022-11-08 07:24 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @svitalis123 :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Gitflow
:heavy_check_mark: Following Requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._